name: NLOTD
favicon: null
layout_spectrum: 0.8
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e4043d'
    - '#e9e9eb'
    - '#8d3b14'
    - '#0a0004'
    - '#d3af85'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose:
  - name: shares
    item: null
    url: null
